Filtrer les propriétaires par commune
3liz/QgisCadastrePlugin pull request #275
Opened 2020-11-16 15:34 UTC by Gaetanbrl

Cette PR permet de sélectionner une commune dans la zone de recherche d'un propriétaire afin de limiter la recherche d'un nom de propriétaire au sein d'une commune.

Ce comportement est décrit dans l'issue #260.

L'interface de recherche (combo) doit s'insérer sous la checkbox de la PR #274.

Merci au Pôle Métropolitain du [Pays de Brest](https://www.pays-de-brest.fr/) cette contribution et les tests réalisés.

2020-11-24 10:03 UTC, MaelREBOUX requested changes
Le comportement est OK pour moi. Si on choisit une commune, on a bien le bon sous-ensemble de propriétaires recherchés.
Je valide.

2020-11-24 10:03 UTC, MaelREBOUX commented on cadastre/cadastre_dialogs.py
> +        print(sql)
à supprimer !!

2020-11-24 10:03 UTC, MaelREBOUX commented on cadastre/cadastre_dialogs.py
> +            print(line)
à supprimer peut-être ?

2020-11-24 10:03 UTC, MaelREBOUX commented on cadastre/forms/cadastre_search_form.ui
> +           <item>
indentation

2020-11-30 09:02 UTC, Gaetanbrl commented
merci @MaelREBOUX - adaptations faites.

2021-03-11 09:53 UTC, MaelREBOUX commented
en attente corrections @Gaetanbrl suite merge #274

2021-03-16 15:12 UTC, Gaetanbrl commented
@MaelREBOUX adaptation faite ce jour. En attente de test, retour et merge si tout est bon.

2021-04-12 12:19 UTC, MaelREBOUX approved these changes
ok : ça fonctionne

2021-04-12 12:19 UTC, merged

2021-04-12 12:20 UTC, MaelREBOUX commented
juste pour trace : si on cherche / trouve un propriétaire, si celui-ci est juste co-propriétaire d'une parcelle bâtie : ça ne liste pas les parcelles en question.

2021-04-12 12:21 UTC, Gaetanbrl commented
Merci @MaelREBOUX